version: '3.7'

services:
  app_openweb:
    image: openmeetings(local build)
    expose:
      - "5443"
    ports:
      - 5443:5443
    #  - 5080:5080
    volumes:
      - ./openweb/openmeetings.properties:/opt/openmeetings/webapps/openmeetings/WEB-INF/classes/openmeetings.properties
    depends_on:
      - app_coturn
      - app_kurento
    networks:
      - app_network_openweb

  app_kurento:
    image: kurento/kurento-media-server
    #ports:
    #  - 8888:8888
    environment:
       KMS_TURN_URL: USER:PASSWORD@HOST-IP:3478
    depends_on:
      - app_coturn
    network_mode: "host"
    #networks:
      #- app_network_openweb

  app_coturn:
    image: instrumentisto/coturn
    network_mode: "host"
    volumes:
      - ./coturn/my.conf:/etc/coturn/turnserver.conf
      


networks:
  app_network_openweb:
