version: '3.7'

services:
  app_openweb:
    image: guzhavin/openmeetings
    expose:
      - "5443"
    ports:
      - 5443:5443
    volumes:
      - ./openweb/applicationContext.xml:/opt/openmeetings/webapps/openmeetings/WEB-INF/classes/applicationContext.xml
    depends_on:
      - app_coturn
      - app_kurento
    networks:
      - app_network_openweb

  app_kurento:
    image: kurento/kurento-media-server
    ports:
      - 8888:8888
    environment:
       KMS_TURN_URL: openweb:openDtcmfsa@HOST-IP:3478
    depends_on:
      - app_coturn
    networks:
      - app_network_openweb

  app_coturn:
    image: instrumentisto/coturn
    network_mode: "host"
    volumes:
      - ./coturn/my.conf:/etc/coturn/turnserver.conf
      


networks:
  app_network_openweb: